### ISSUE TITLE
Blank UI in HTML: BackGroundDemo and others

### ISSUE THREAD

**Issue by rfabbri** [threerings/tripleplay#29]
When I run the tripleplay demo, the "UI: Backgrounds" is not working in HTML. When I clck on "Backgrounds" in the demo, All I see is the gray screen and the "UI:Backgrounds" title, and the back button, but nothing else.

Tripleplay version: Git  2013-01-03 sha1 0c0fe1e110066cc8cc1836467af3027134085240

It does work in java, though. (jdk 1.5.0_02) 

Not sure if this is related, but I also get a blank screen in HTML after having inserted UI (ToggleButtons with plain image asset icons and no bevel) in my application which previously had no tripleplay code. This occurs with tripleplay 1.6-SNAPSHOT from maven. 

All of the above issues were reproduced on Firefox 17.0.1 and Chromium 18.0.1025.168 on ubuntu 11.10, and also on the ipad 1 safari browser. The ubuntu box has a GeForce Go 7400 video card.

PS: I'm completely new at this (java, playn and tripleplay programming), but will benefit from any suggestions or pointers you can provide.

**Comment by guillerodriguez** [comment]
@samskivert This seems to have been fixed a long time ago. Issue can be closed.
