### ISSUE TITLE
The RSet of TypedStorage.setFor() does not handle the empty set well

### ISSUE THREAD

**Issue by cdietze** [threerings/tripleplay#39]
The problem is that the stored string is "" for both the empty set and a set containing just one empty string.

https://github.com/threerings/tripleplay/blob/master/core/src/main/java/tripleplay/util/TypedStorage.java#L295

As a matter of fact: `"".split(",").length == 1`

I guess it's necessary to add an extra check for the empty case and removing the key when writing to storage like so:

```
if (rset.isEmpty()) {
    storage.remove(key);
    return;
}
```

**Comment by guillerodriguez** [comment]
@samskivert This was fixed, issue can be closed.

**Comment by guillerodriguez** [comment]
@samskivert This was fixed, issue can be closed.
