### ISSUE TITLE
addBarrier behaves different in Java and HTML

### ISSUE THREAD

**Issue by tulsidas** [threerings/tripleplay#54]
I have this snippet of code:

              float DUR = 600;

              fanim.tweenScale(photo).to(0.25F).in(DUR).easeInOut();
              fanim.tweenXY(photo).to(-10, 370).in(DUR).easeInOut();
              fanim.tweenRotation(photo).to(-FloatMath.PI / 8).in(DUR);

              fanim.addBarrier(333); // wait for the current animations to finish and then wait another 333 ms

              fanim.tweenXY(photo).to(-300, 270).in(DUR).easeOutBack();
              fanim.tweenRotation(photo).to(-3 * FloatMath.PI).in(DUR);

The desired behaviour is to scale, move and rotate the photo (an ImageLayer) all three at the same time, then afterwards wait 333 ms, then again move and rotate it out of the screen.

In Java this works ok, but when I export to HTML, it doesn't wait the 333 ms between the two sets of animations

I tried different combinations of addBarrier, but it didn't work :(

I set up a minimal project in github that showcases the problem: 
https://github.com/tulsidas/tripleplay-barrier-demo

The code is extracted from the game that originated the problem.

There is a standard animation moving a circle, and if you click anywhere, it will take a snapshot of the screen and animate it. 

On the java version it works properly, the snapshot goes to the corner, waits ~3 seconds, then goes away, but on the HTML backend it goes to the corner and immediatly goes away (not waiting the ~3 seconds)

I tried it both in Chromium 37 and Firefox 31, same wrong behaviour in both.

**Comment by samskivert** [comment]
I just tried it on Mac OS Safari, Mac OS Chrome and Mac OS Firefox and it worked just fine in all cases.

I put the version that I built up here: http://samskivert.com/play/barrier-demo/

Can you try that and see if it still fails for you?

**Comment by tulsidas** [comment]
Works on Linux Firefox, it wasn't working last time I tested this (almost 1 year ago)... which playn+tripleplay versions did you use? I think I was using 1.7.x

**Comment by samskivert** [comment]
This is using PlayN + TriplePlay 1.9.

**Comment by tulsidas** [comment]
Then it was probably fixed somewhere in between. I'm closing this issue, thanks
