### ISSUE TITLE
Touch events in mobile browsers immediately deselect toggle and dropdown menus

### ISSUE THREAD

**Issue by doctor-g** [threerings/tripleplay#58]
Using the latest snapshot code of PlayN-2.0-rc3 and TriplePlay, there is a defect in handling touch events in the HTML builds. Touching a ToggleButton causes it to be selected and then immediately deselected, and similarly, touching a popup trigger causes the popup to appear and then immediately be dismissed. The problem does not arise when one starts by using a long-press.

More details about the problem have been shared [on the PlayN mailing list](https://groups.google.com/forum/#!topic/playn/lAP3IDi-ec4)

**Comment by doctor-g** [comment]
Can anyone share some insight on where this bug might be? I started trying to wade through the touch-handling sources but it's slow going. I have two projects that are held up by this issue. @samskivert, maybe you can point me or my team in a useful direction?

**Comment by samskivert** [comment]
The problem was that Pointer was listening for both touch and mouse events, and on mobile HTML5 it generates both kinds of events. All other platforms generate one or the other.

Fixed in playn/playn@3333971237bc3836d62d6c20a4464411b4568d4a
