### ISSUE TITLE
Maven clean install compilation fail

### ISSUE THREAD

**Issue by pradyp11** [threerings/tripleplay#59]
Hi,
I have maven clean install compilation error. 

JDK : 1.8
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] C:\xxx\TelemetryState.java:[99,183] error: package jdk.internal.org.xml.sax does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.318 s
[INFO] Finished at: 2016-08-22T12:24:36-04:00
[INFO] Final Memory: 17M/189M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project dev-sdnmon: Compilation failure
[ERROR]  C:\xxx\TelemetryState..java:[99,183] error: package jdk.internal.org.xml.sax does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by samskivert** [comment]
There's no class named TelemetryState.java in tripleplay. Can you include the full Maven output or double check that you're compiling the right project?

**Comment by guillerodriguez** [comment]
@samskivert Doesn't seem to be a tripleplay issue, should probably be closed.
