### ISSUE TITLE
2.0.2 is missing in maven central

### ISSUE THREAD

**Issue by cdietze** [threerings/tripleplay#69]
Only 2.0.2a is there. Which makes it awkward to use since playn and tripleplay versions should be the same.

**Comment by samskivert** [comment]
Yeah, sorry about that. I had some trouble with Bintray when doing the 2.0.2 release and was not able to re-release TriplePlay 2.0.2 (which was broken), so I had to do 2.0.2a. I guess I can make a 2.0.2a PlayN release, but that's kind of annoying too. Maybe I'll just release 2.0.3 for both libraries and declare 2.0.2 to be an unfortunate accident.

**Comment by samskivert** [comment]
OK, 2.0.3 is shipped and hopefully making its way to Maven Central's servers presently.
